"""Embed processed painted atlases as data-URI JS modules (file:// safe).

Reads assets/processed/*.png + metadata.json, writes three modules:
  assets/paintedEnvData.js    (floor, dock_doors, conveyor)
  assets/paintedPropsData.js  (pallets, cartons, carton_bands, dressing)
  assets/paintedActorsData.js (worker_A..D, rc_operator)

Each registers into window.PAINTED_DATA[name] and window.PAINTED_META[name].

Run:  py tools/embed_assets.py
"""
import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "processed")
DST = os.path.join(ROOT, "assets")

GROUPS = {
    "paintedEnvData.js": ["floor", "dock_doors", "conveyor"],
    "paintedPropsData.js": ["pallets", "cartons", "carton_bands", "dressing"],
    "paintedActorsData.js": ["worker_A", "worker_B", "worker_C", "worker_D", "rc_operator"],
}

with open(os.path.join(SRC, "metadata.json")) as f:
    META = json.load(f)

total = 0
for fname, names in GROUPS.items():
    lines = [
        "/* AUTO-GENERATED by tools/embed_assets.py — do not edit.",
        " * Painted atlases (tools/process_assets.py) embedded for file:// loading. */",
        "window.PAINTED_DATA = window.PAINTED_DATA || {};",
        "window.PAINTED_META = window.PAINTED_META || {};",
    ]
    for n in names:
        with open(os.path.join(SRC, f"{n}.png"), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        m = META[n]
        lines.append(f'window.PAINTED_META["{n}"] = {json.dumps(m)};')
        lines.append(f'window.PAINTED_DATA["{n}"] = "data:image/png;base64,{b64}";')
    out = os.path.join(DST, fname)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    size = os.path.getsize(out) / 1e6
    total += size
    print(f"{fname:24s} {size:5.2f} MB  ({', '.join(names)})")
print(f"total embedded: {total:.2f} MB")
